# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52bddc857e4351917687e0f8113b0b493951e8c24f337f0f2c40f23c98cfb9d2d7bd63da7545ebf3f1cf6e8f4dae32ad83911a754b38aedb648b30d2d05e9d8d

test:
  secret_key_base: cb7280bc218186a4aac5d4df15007930f0b50128621d43c1af44b301c15ac3d81ce7f0c5f23b3279154757de249beeb0ac48866627e05a54d147a82e8d018f03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
