# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13885a234af5198d5f9fd3afdf3ae81e51cbc0d2fead2f79697e21011f38ae75b19a26abc88604f9c168ae4ecc364c11e8c6d0afdf6413b366324ddec9773578

test:
  secret_key_base: 80303888ccd5bd573984f16a3b4890c9400e996feb6ac4a02d389e1e6ab984c0c4a11368d8059aaded0ce50cfc7c2d64b44028207954d05b0b92c08750c3b503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
