# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28578685d744f97f128fb8f6c8a24ce65a3d0918e8b60e916b367fe09fc3a3e799f42c6df4031a1f1b0e9211fb466cc5e1dc2cc257101954432cb6e224d7cc57

test:
  secret_key_base: 556ae447e8d7a3b6e7aa9227b210dc0dd454a74cfba91774a1f099620afcf13c8899a76142ec2e407d15f3cdf547f57453b82a3b2e97c543ab38237cd4ccb446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
