# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b4a05b531c9f388d1d7759ca502383a29ea5433d51004071eeffed506384677b5c0ffd57d5ff79df65222370868981c7017bf1b7554d125d0f52f23396de0b7

test:
  secret_key_base: f2583addb31c9215972da33d5eea6013ed51d9608461da1f43fb7ca8464984fedeab4225d1c427826f99b9ead565cd6615d0eb47001abeee828fc1583d941958

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
