# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1de18bfad70c46559f6a3bdfa28ce502e320ea92f6a3d4582005c63112dd5e0a0c6290e95d9c08f1ec56a7fd0031d6cdace7dad0a9c3eb1df750b7dbeae77d7d

test:
  secret_key_base: 23572166e8efa2845ee1939959646385be97e32db2eb0630969212bd301320b422486338f3e7758f74f19f13fba6c57713dcab9facd3f9d9a8b0b39b47f76334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
