# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1b36a4aaf6fa9199e610993ad093921e5a8d8d5f8dc4195ab759773683b797f5bbe1d2a07d75ce9c9fadf2fbdd773e31b9022c4797d0de41266cbbadb4d23dd

test:
  secret_key_base: 2f45af52f5b40194940190f75a974d40b08c68e5187b2c4f0b98ae86bc99740980e370b21e140e1a51f74e7dec9a1fa0f296e2b6b378033436d389dbd6dc8d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
