# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 195e9d312ae4a5cdb281aaff420947efb4d7fbf9187e3357dd228324441f29ce67cd45025eb994d4f2d0993cf4bfcae37fc39ecbe457eb9105f55cd8dfbab32d

test:
  secret_key_base: 56576f181447b9d8e4cb7a73379501c3fd82e183b3cb06cfcfbe57f0b5176c0d8ed604623b5586ca0642aba06266d23d48ccdd14b0038cdc6d4356081c089502

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
