# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a45a26b99a63fec2ec9dc19790735f363c585994c3a91e942994a2e92ec76f1845676490c99466f85564d6f9c7b2316b6af8a89cb9e24037fb9e52f48b2e2082

test:
  secret_key_base: 5fdc98ffde868256791c93b122251abff1b829f1143615fae9965f5a7584882d63df099241c665a6667168bfad552b272c7d5957fae6ed17ff10247ce3e84d6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
