# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8c19e60cd045683e8572d292d699a3c2929fce45c278f2d1a9cf54a44946d6effbff753924f0bb0988f06c3d37d4cb45945183c0231499d79ca400d23aa1683

test:
  secret_key_base: d682eb5287430ecadb58f960d3c5709aba784fc56492ac3c38b72c99a991a29159d343f657146c03baaa90a9bfc9bc01510a6a769b3091880eee82174a86cde6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
