# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e553465017fa5b7773a8be483e6f49449c54e4948d9ae8c23369a16bc938534beb37316a619d67e6006bb94a9bfd04c67cc4fa4b7db10467017ba438912d01f

test:
  secret_key_base: 3003f5133531cbda0e576ddf8f025d987b3fd6b09ccff705274bc4bf3efce55419a0f544b093f6857bd06dcd998611faf5f6dfb6c625fc803c87567a004ebcc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
