# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24455a40074a77b145b2e142144b1f2fb4dfe5dea646b797c2369f5a999efe02f719e01216f3831a517be86819ceaf343dc92293e71df78ae03a479198326a0f

test:
  secret_key_base: 3f0e58e6b4738ffdbcdea067498896116cc432139daf4a9b5183daf4ec66db4df6b15148aaf9bcdf6601f176f6a880142138151026ae65916b945ad607e5ef3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
