# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27c2686603123284dfabcd156ae6c3fa744ae118fd0a930e05b20980909ca9de94282f45ef1de2a4d0a3c8e242dc5387faaeb47aadcfcff43d2595533e49d4b8

test:
  secret_key_base: bc45c8ff75366979b60e98068270274c2a70d834dce011bdbb81085083f693a4891f53299b77df8e2d489a8ac4415953248094389f552fcf9a2ad7eb73c75194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
