# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e60e78cf5f1cb70d9acf17d2a19b5a9419d7e421b7e90f5081f42cbfb2f4bf6834ee032bf39cb4a56e6fe61d082d49d157c53305a02b2b26d516f1a70255944

test:
  secret_key_base: 589557feb94b4710285d6597fba939928d3017240bc02b9abed201ed17ae140f0791da25de515860198bca9ca9216843ded9fb95ff75dd51cb1845ef29736ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
