# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358d02f2e363ff7275f4b13c6226c74d5a6a1419630d906f7da3b61bfe0465ebc01dbd7b4bf98afa69119b5231c3f955b87a5b8971e2958b3b1cf07b95b8a58c

test:
  secret_key_base: 25120dff40fe63cbb00e49b480c735f71bc6df4bec29060f5d149614236f0d57935c3038fcabfb38b0635f4fd4e75ddb138cf5683725ed033a68b65c5d5e3695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
