# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0d3794748245ab592a796a61f9d3a3289119edec983d1b39c745a2c7c8aa17d60870a103d72a6c3ca97cd7011ca1338a85a7f8a637bafe2e7bb78458de29176

test:
  secret_key_base: 48c63ec79530f48bac126d5330f47bbfa07a38fc645d2af582ee0c50366e91db704df730d5109cb4072d178bf1ced7534d56d331df47a5df67b64de6b06631df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
