# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 507e930f281dacefa2d30366c603a76bab9a6e9e27f6f6ad9c1d6af065125b02d287ea1419f08417694335c38e6b3254a67b134972845b18a33fc6af3822ee52

test:
  secret_key_base: d1eba3a8a7f607918558724d17c25d8408944a16dc9bca7ca79064c20a39bfd12c653227aa3855f2d4c8aa3890de3ce0fca56b6f072bbf247dc3a28bda17c5f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
