# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28359112c1ed9864d6c03435001815db9ef58928fb4823a9cfb3ba6ab55009a8ef08096ba462bfaf1146a3a17f9451d9c6027a7cedf87a23688d2e6a0832ae42

test:
  secret_key_base: 34200395a165850417a882b0128432f26d9abdd46d9668edd677ce71dd883677467ae05b075cac2c0d0330e82cc85758df14fec3ad9d07ff54cf35043baed3d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
