# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bea690899fdebfa86f3095ddc6407f7183b1ea7162def68b0a8a3351504b5a32832a9aff82922515365f98278d10635fc0cf69cca5981f903b44d06974aebfe6

test:
  secret_key_base: fdb60d0694f161adb6811abeecb8af02b5ad6655cb5e919ff1a8625eaa590ac0f7174cce4f7772e66181c664371dd543cc034b6d7adc572b3893dcb7a4c542f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
