# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 061442ab5435547fbe6bf46559a272d099f84969e2eb8e86cb18248510de01dfc0218b0bcc418a80e0d3f764963bd8199125d363eb047905303a8a734925bad4

test:
  secret_key_base: 6b9e934567e4e3e5a4a1e92a5f11886bcc96714f0553f5fa3f062c01083a6c982a6c8115f04e397fb26da6be6bb36b96e69121bd794ebb987c928f407dcb6789

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
