# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c922155ebfdfb1bb871196ad9ce89f0c823407758981fc2488fb0419fbd1b8eaea25980cf6a82d94d9317261147cd96cde62df306adeb236605fab52866c456

test:
  secret_key_base: 11c21df319d6a37b64e7daa9ab346d1471c53ae48a78fc8157e84f0bec700354a8b7eb0d655ce3a2b98b548bcae4010ee78be9717d991344e7063b8b6ea17f87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
