# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7c529ba7b75ab39082c87ebb541f5c9ba48363afb02ca3c0b53dc31a2f6cdd0f98b71c7e9dc57bc92712452ce433e2bfd6529b7b3825f5e07df2da881839abf

test:
  secret_key_base: 2760c38d686671c14ed72d229e2acc6ed341503c154fa1869438d08cf3f6b7e160f83a551a5821e1279b99a363356b2f817738f9e90d1c153f98964df7ee563e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
