# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46c01e500ce890a08354b0ca5f31a307e086e96340becc90bd81c6c765ea0f68b48bbdb578481b71ed8ba4016e767a72682b30446de1360b912e9bb9faec227e

test:
  secret_key_base: ee2636928e6b551a222beaae0ce907c1c00127b97fbf67ebdcbb709e0e0e4c35e2f1ea7d6157ddb70648872d8010ee8633a66a8833faa8b73b76390cfe316aef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
