# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e2fa8f663676346c5180bf8cddae9125710b5d57507ed3f37ac3244f73d11f904ff4ab4f4bb33bb8130b8a8b6c26350d067049f331ea10a07664d4f34a8703

test:
  secret_key_base: e55cf2912469748b903323e7168faae329c136b71890f524318881f842190c3dfec2a4f245f9127e016723b564c694fdf5d26562df2e6927a341e1c3f796c288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
