# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8786e6ff4d1d3bec5cb92ec56e4efc81d2b13258eec950c900e270d41bbfe6bd1cbf99cae452246454fc9d2dface302b8269cacb9825f46d5ad28ae6cdaae114

test:
  secret_key_base: ffe7eab57720c151567f7d21f00a282e05940587b67a14a23acae1b1eb6ef076e082547a36eb8762f89ab5b13d10084431375a701760ce59ab26a6e4f531eb5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
