# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e845605a21a9767d32989f9ea3dc41fd677db6fac5c31048f6b2780a7f6874f141b403ba41a1a33b5660d6231dd3b591d3a82e87210123050c4dbf57cf7571d1

test:
  secret_key_base: 2f45403a379de4cba8d4446ce8e4c29a2e30793f5468c2551ea34d4c45844f016002329985a3ace6ad2444974901b9931b1e05bc7b56e916499f036a2270ae0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
