# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a84e6f615113a304ec1c93ded35ebb7704808828c0c1c7abf7cd332fa47d57c6c1a78495fad7c39485dde7eb0f9f410435fd302e9caa5d53dec3994d714a87a

test:
  secret_key_base: 333ec0d895c2d67721cbcb5c2d39fd4ad9a772cb2024e9e80fb352256c83eabdb7e11b084656c45e1a2fb2bbb49dc8706f81d7ea6b605db6c31e49cf9377ba89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
