# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a44607c96ad8310ea23ebde04811f4a206972f87b4f504d9a0a121c67dfde83212cd16b3c3bca74e2dd23fffd546dc59a6d07bcb0c1e3927f0396f6a1103dbab

test:
  secret_key_base: ca891ed27461e4ba1f00380337ad89de3a802994bf0bbdd4f5534a71b067a9c3a92191bd1c98f07a0fd93517bf427fbe1ec37ebc0c2113aad66cebcf40261d90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
