# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd139b6624cac9721df096394ea08da533d716b80c21e216b85f9fef792aa4526284e98613b482e117df261af6f0a508626278f95a302aed127251b1ec6fa59

test:
  secret_key_base: f0003d3ea7f7d7189804f3c31d8dd87b0fc045bb244650be8bb651b98d6a132006ae3010968c6b0e5c6eefbef28328621473ceb26e7020f090a3ae9be259964f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
