# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99b225808a82dc9aec16aefc5d6f8536de6a60a52c6ace2345671d78d5264195a29f8d24d33085e49d85a6f1b0fc0388e3aff73ea2f894bc4ad336c4f94e6e1

test:
  secret_key_base: 1b74370db9f077898d7c20779cac82cb693587ea96fae83e2a5a6606ea0b9b29b9ef316e45a9901b3f77c0034f1237437393816e1d6afe478e92b755446569e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
