# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca3bdf84e37297fb4d0ef7e2a899e39ba7ec994aef177e4482cf32a5fbcc175583b30df03b322ed6f717be3b891d0720739af35607d388a8bf2888a235203ebc

test:
  secret_key_base: 73ed9f239cd6309cd20f2bb603080521803397b5f3f79fb193aa7b59dad75de8b5bf43f239f8580af3e5465751fa1db24f0a9f3b7069bf8edfaf43b5bd9b4bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
