# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e0ed4a6f18cc3127399e16c9c15cfec64ecdbaad91649e1aad82bb9e8ffbd153230ae16d589edb0fab5fbcc0abde68d9ce17c6e62e64873812d79d0a66ebfe8

test:
  secret_key_base: 189627c4b3e1a9955adb9dccbf8a6b86ae1382b0aa16cab21b133f1c2946653d2c8d060f1ca955ceed730304a08a231996958166c8ce48706c92d3415935b87f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
