# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c76b0c78789c2519cde05cedac254473db551bc42fc69400492947431fb96553af13c12172f44b4dc68183adfb02f5e1a6c8170eb7eab7815de20c8e47afbd1

test:
  secret_key_base: 4bc19dab7c09176562de438f51bdad9e0a93d940ab5893880542a3215373ed2f27e0378ba90011a260ed38ce0126541e946b32365be5699e1596dd87103529e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
