# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c092c9e13f4703f66dcf68e7c386c510a176c35b1eaabfafcde432938108e4b943b71c64bd54ceec8be9a4230195319764eaad10e50e68ae34d199cdd50718b

test:
  secret_key_base: 6a3b03aefe1966ba70ec52d581e420f546cc696e9e2caf93e8c7e187039b3839d0ce35a6d20f9d49290eadfe5c7ffbddbfd69d8a8eb1f64a4ca5ea4c3bde5588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
