# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78c44c6db10e64c5886cbc8bf919e2457416cc59d4f7334d1363f49349d204d8fce7b17675834ea2500d2e27ecdf9073d675ba7dde91b26885b61abf2e9d78d3

test:
  secret_key_base: 5902aa92faf6965b0e61deb025ea2f3c54cb4b72dfb17a5ff982bff7369d8ca85ccdb4d57c31c8e16b23ceccf84e7f96087fa06ae9d8cbc8c13b3b94716a1051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
