# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bc2952550f8d33ccddd2f59b88a20676601480dd9ec4b0a06c5185c36641ef8bb377a2b0abe35ed1c06130af79b71ecfbaf893da2cf14199ad4afd5b85230d0

test:
  secret_key_base: e7055284fbf11f77f8df704e41298b1685dde1c863c6efda43f856f9808b2ddbcf8fb13b4995738febcca5c46b39ad0bf528ab05c3f52cb9774742432c41174b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
