# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a1fbb9ddb5730d96f979c0500d388917a6722e184ef27009c3c8b00e86b2dd68abdd999d28ea6f4a0271ebb39189f74e25e8f51ee97714d74089a3831a403d9

test:
  secret_key_base: baa40d2ace3ce63d41388785b9f45030a20267fb277565b7bf0ccf1cd2bd5fc770c4e70a820dc4e002e453bd500ce9044594ec5e8db9d2e27611b50ca9565b8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
