# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 079cb65cad325f995f04f88eaec3179f2b75a1ea62fd7e23921af3ecddd892398cf1d124f5d305531a16ee4b1a7696aa91af4401c613f94a3a57c204ad0e77a0

test:
  secret_key_base: 0979b8340ac67278584ae6d3096ec7347ed5c99c1aef3306cecbc23a0749856ac87278f2df1394eb1dbb72910a0d9a9880eab74b29d4cb8ef807386ee31c6ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
