# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08f5237c307c4d97728ec0e4104022e18ea7889afb4a23985fd5c193dec1ff1a828631aa690aac33c8de4958d29b7852a067cbece1a38d320b097e3d9096fe42

test:
  secret_key_base: 1d025cce7f36d7eb20c8c46a5d48f4af84adba3ed118e8e1a0d271bf6bb54e2288e37920da59f612cafe004636275453ea2e926e5efe4819419cf2beab2952d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
