# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3605f18bc169bb7dc6956c5ec2205ded48add202463423657e38e69067d0aff1d658871bff8c02c9ef25b7e9b6c911a4b921a061573d19bbe60a0bca923396a6

test:
  secret_key_base: a877f5816cce55b8a9adfd71434c5bed1ebe1356b90eaebce367eecea7a86b28fff9503228af791f5bfc7697cd525e96289192beed69ee7a01821cbe4548ca78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
