# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a1d5f8e888777525250aec71863514fe240f921ab744bc8d54b1638ef2bc1685e7b4cfaebe76b3c7bc436190709e7d05f0ee15f076b449468c866d4235974a2

test:
  secret_key_base: a5d1855ad4fadbd40a94c4b84bcb6e895796a562e709d470e0df5a8ddb55395d537a3c08c85845ab2c4a92fbc063121cfdb569bc30a6f6b19ece725dfb186964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
