# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4162790aaf020f8e97b899ef35c5f541a8fa43cb409b0b7bdca5d013ba29993fbd223d1069283f79aefefc094a91433e81dbe6d5a072187a24392c004071f31c

test:
  secret_key_base: 5c618a615a2cb819a037860573261068c5b0f07ff6e21c2c5f410478c0319cdf5a0e2171cf4953ff312100a4e6639e56c79792cfc16b00fd2be78183178f93fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
