# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce8949e9463a40d4f94aef9a7c545561d5b7e9f2586f1423dff39654a29802135597f05913b6207e213d9f7a239e5dceda616c0bc93733e8dc95e022550ec13c

test:
  secret_key_base: 4639c6237b60cc6e05f021ced4705b9500596de9c2941f64c768fb5bed83b2e278a94fda5f639e0da1d11cded7904eea1a4b1087b473f8ed67e208a23397f1ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
