# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f7aa0d7db803b5e0d75317f3833f86de59c7b5ab95f6eb681880e23b697c47d9acd540cc3bb10dd6d24a195afb753cd020f7ec887fd829f5ab67c5a1f8ed85

test:
  secret_key_base: c23d151e1adf17ec465618c0308f67537b3272c93daf666023d7c7fa3413e9e20e3ec7ee62933e2b4c3c4f09ef25b975c64ca3fa6fc071cfffcac1e09adefed5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
