# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3290a8508ad0908251af1eeae1edf609c59050f8d764bc81b9902fce0671380687f7fe410ae23a5e58967be8ba5ff66aad01411a79c59f5f0a9f2e80d8d59c80

test:
  secret_key_base: 0fca45a2a5b0680750f04321273bf6caff5c0b8c0bb946872655d015642880f55d4e435738b13df16ae66900b9a6840fe92b01233049540287efb099bfcb096d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
