# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8220eebff0ab94862e2152327b4985bce4ae42dbc9ac81f3257067d4b6aaecfb06ba9985c5af42a0a1afc3c633d0228b420bd7a23487e3ac4ccc37605eb8c4c8

test:
  secret_key_base: 905503b52a2d9a75016db9765400bcf5989bfabe02c17697048a36996cc7a704c03cda3f9dbb89c5b6ef19ddcc14908c294c08621b915c5c744f41cdb809aa3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
