# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9821e8506dc2de08bc6a47d2f21d4d6e64bb0abd3610bd49d194d7ec1027e26d1ecc2349888811bb79d7ba47b63a12ac2b5a2904a73991ef92baed3ffc0cd6b

test:
  secret_key_base: 6d5b4f599b8de61019df53d8e2f4e817b97f030b49f5a0ed1679169e43e881d5da9de77179f92013a3b8a108a7b61d1383c6565d388f995e3e6816d33c99c247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
