# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 428d0fb2ddf18c6882f098f5d891ef9adc14ae764f2ac94a904ae9b6b1044120fe42d984baf11b8db25a0f57f1f1b21e0beaf39fef4878fe5e1919ffb16dcc1f

test:
  secret_key_base: 20666661b8fb9b8f04a8128ce099074b100702f8d24009a579316e0b57579da15036271784d488518dab0dc81db04ee09f8bdebe4a9628bb51bf8df2476546cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
